### ISSUE TITLE
NoMethodError: undefined method `get_feature_flag_from_key` for nil:NilClass when calling `get_feature_variable_*`

### ISSUE THREAD

**Issue by ramimassoud** [optimizely/ruby-sdk#107]
SDK version 2.0.1

On occasions where fetching a valid datafile fails, any call to a `get_feature_variable_*` method will raise the exception `NoMethodError: undefined method 'get_feature_flag_from_key' for nil:NilClass` instead of failing gracefully and logging.

Within `Project#get_feature_variable_for_type` there is no check for if the project is useable via the [`is_valid` attr_reader](https://github.com/optimizely/ruby-sdk/blob/c1ca00d7a73581fd5fbafff692e343490d8448b3/lib/optimizely.rb#L35) before attempting to access the config

https://github.com/optimizely/ruby-sdk/blob/c1ca00d7a73581fd5fbafff692e343490d8448b3/lib/optimizely.rb#L439-L449

All of the other methods seem to return nil or false if the datafile cannot be parsed

https://github.com/optimizely/ruby-sdk/blob/c1ca00d7a73581fd5fbafff692e343490d8448b3/lib/optimizely.rb#L262-L266

**Comment by mikeng13** [comment]
Thanks for submitting. We'll look into it.
