### ISSUE TITLE
AsyncScheduler rescues errors but doesn't log the error

### ISSUE THREAD

**Issue by jasonkarns** [optimizely/ruby-sdk#205]
https://github.com/optimizely/ruby-sdk/blob/45e7e2b87041d9fc81d047c17c5c6429a0a731e5/lib/optimizely/config_manager/async_scheduler.rb#L78-L82

It rescues the error but doesn't log any of the error details that are necessary for tracing/debugging.

**Comment by mikeng13** [comment]
Thanks for reporting! We will look into adding more details for tracing/debugging this path.

**Comment by jasonkarns** [comment]
bumping comment: https://github.com/optimizely/ruby-sdk/pull/212#pullrequestreview-326232686

**Comment by Tamara-Barum** [comment]
Closing as linked/Merged with 212 & 248 in May of 2020
