### ISSUE TITLE
Gem is missing the LICENSE

### ISSUE THREAD

**Issue by jasonkarns** [optimizely/ruby-sdk#206]
The distributed gem is excluding the LICENSE file because it is not present in the spec.files array: https://github.com/optimizely/ruby-sdk/blob/eb0c6d6ef0bac7c19d4d6e6e88b54b167e89ea9b/optimizely-sdk.gemspec#L16

**Comment by mjc1283** [comment]
@jasonkarns Thanks for bringing this up. We'll release a new version with your fix.
