### ISSUE TITLE
Make REQUEST_TIMEOUT something clients can control

### ISSUE THREAD

**Issue by jeff-hired** [optimizely/ruby-sdk#21]
Can you make the HTTP request REQUEST_TIMEOUT variable something clients can control? 10 seconds is extremely long and something I'd be uncomfortable with.

**Comment by delikat** [comment]
Thanks for the feedback! The included EventDispatcher is intended as a reference implementation and as such it isn’t the right fit for some environments. If you need custom behavior such as a shorter request timeout, we recommend implementing your own EventDispatcher according to the reference implementation.

**Comment by jeff-hired** [comment]
Yeah, I see I can do that, just thought it would be nice to have a way to change the timeout since that's the main thing I'd want to do differently. I'm fairly happy with your dispatcher, but I could just override it.
