### ISSUE TITLE
Feature request: eliminate HTTParty dependency

### ISSUE THREAD

**Issue by jasonkarns** [optimizely/ruby-sdk#211]
In a large Rails app, the number of dependencies can grow quite large. In such an app, the risk of unresolveable version conflicts between versions of a single dependency grows ever higher. As a library, it would be very helpful to consumers if the library's own dependencies were kept to a minimum. This would minimize or eliminate any such version conflicts.

Case in point, the HTTParty gem is a dependency that _could_ be removed. From what I can tell, there are only two small use-cases for HTTP in this gem: [event dispatcher](https://github.com/optimizely/ruby-sdk/blob/99512e4c845a44024003be685d1331560c5792bd/lib/optimizely/event_dispatcher.rb) and the [http config manager](https://github.com/optimizely/ruby-sdk/blob/99512e4c845a44024003be685d1331560c5792bd/lib/optimizely/config_manager/http_project_config_manager.rb). Neither object has that much extensive use of HTTP.

I would request that these classes just use [net/http](https://ruby-doc.org/stdlib-2.6.5/libdoc/net/http/rdoc/Net/HTTP.html) from the ruby standard library instead of pulling in a dependency.

**Comment by Tamara-Barum** [comment]
Closing as linked/Merged with 252
