### ISSUE TITLE
CLA missing section #7

### ISSUE THREAD

**Issue by jeff-hired** [optimizely/ruby-sdk#22]
The CLA (https://docs.google.com/a/hired.com/forms/d/e/1FAIpQLSf9cbouWptIpMgukAKZZOIAhafvjFCV8hS00XJLWQnWDFtwtA/viewform) is missing a section between 6 and 8. What happened?

**Comment by delikat** [comment]
Thanks for pointing this out! It looks like there was a typo in the CLA. We've fixed the error.
