### ISSUE TITLE
Can't restart config manager after stopped

### ISSUE THREAD

**Issue by jasonkarns** [optimizely/ruby-sdk#237]
The `stop!` method sets `@stopped=true`. So once the config manager is stopped (via `stop!`), it can never be started again.

https://github.com/optimizely/ruby-sdk/blob/44d585926c259f56d09dc5c25dd1e5f1551414fd/lib/optimizely/config_manager/http_project_config_manager.rb#L92-L95

**Comment by mikeng13** [comment]
@jasonkarns can you elaborate on the use case for this?

**Comment by jasonkarns** [comment]
Tests; non-constant polling; local development; event-driven polling (polling is enabled upon receipt of an event, and turned off after a time-limit or successful update; then restarted upon receipt of another event).

Honestly, I'm more inclined to question the validity of an interface that includes start/stop methods that can't actually invoke them. (Order-dependent method invocation is horribly bad. The object should never be able to be put into an invalid state. If a "stopped" object can't be restarted, why not just destroy the object entirely?)
