### ISSUE TITLE
Tags are named inconsistently

### ISSUE THREAD

**Issue by jasonkarns** [optimizely/ruby-sdk#238]
I'm having a hard time following the tags for this gem because the tags are named inconsistently between version. Some have the leading v prefix and some do not, but it's not clear which is intended to be the format long-term.

First `1.2.0` without the prefix, then `v1.3.0` with, then `1.4.0` without again, then `v1.5.0` and all the 2.x with the prefix again. Then I assumed the style was back to no prefix since the entire 3.x release line didn't use the prefix, but now `v3.4.0` has the prefix again!?

```
$ git tag | sort
1.2.0
1.4.0
3.0.0
3.1.0
3.1.1
3.2.0
3.3.0
3.3.1
3.3.2
v1.3.0
v1.5.0
v2.0.0
v2.0.0.beta
v2.0.0.beta1
v2.0.1
v2.0.2
v2.0.3
v2.1.0
v2.1.1
v3.4.0
```

**Comment by jaeopt** [comment]
@jasonkarns Thanks for reporting! We changed the version name to 3.4.0 (from v3.4.0) to be consistent with the previous versions.
