### ISSUE TITLE
Any reason you are locking httpparty < 0.14.0? 

### ISSUE THREAD

**Issue by rromanchuk** [optimizely/ruby-sdk#24]
`spec.add_runtime_dependency "httparty", ">= 0.11.0", "< 0.14.0"`

**Comment by codechapin** [comment]
I think I run into an issue with this. It looks like rails 5.0.1 is using json 2.0.2 but httparty 0.13.7 has json ~> 1.8

**Comment by gaganawhad** [comment]
Hello @delikat! Thanks for your work on this gem. Can we hear from you on this issue? I work on a mid-sized app and the strict version requirement here left no way for me to be able to resolve the version conflict, so I had to end up forking this repo. I am not sure how helpful it is, but I have submitted a PR here: https://github.com/optimizely/ruby-sdk/pull/25

**Comment by delikat** [comment]
Hi everyone. Apologies for the delayed response. I've gone ahead and approved @gaganawhad's PR (#25), which changes the httparty dependency to `~> 0.11`. Once #25 is landed, I'll get a new release out right away. Thanks for your contributions!

**Comment by gaganawhad** [comment]
Thanks @delikat 🎉

**Comment by delikat** [comment]
Fixed in v1.0.2 (#27). Thank you for your contributions and patience!
