### ISSUE TITLE
Feature request: make JSON schema available as a file 

### ISSUE THREAD

**Issue by jasonkarns** [optimizely/ruby-sdk#245]
The datafile schema is stored within the ruby sdk as a Hash constant. As Optimizely is unable to envision the multitude of integrations of the ruby-sdk, nor the many potential toolchains and development environments into which the ruby-sdk will be installed, it would be more versatile for the json schema to be shipped as a standard schema file ( `datafile-v2.schema.json`). This would enable the schema to be hooked into test suites and other tools that (rightfully) expect the schema to be a regular file.

The ruby sdk could still parse the file into a hash and expose it as a constant. But making the actual file available would enable additional schema toolchain configurations.

**Comment by Tamara-Barum** [comment]
My apologies for the delay in response to this issue. The team is updating our processes and reviewing all open issues and PR's. If this Feature Request is still relevant, please add your suggestion to our idea portal here https://feedback.optimizely.com/ where it can be evaluated with the other ideas for the product.  From here it will be appropriately prioritized and brought to the engineering team.
