### ISSUE TITLE
Feature request: Datafile schema validation errors should include details

### ISSUE THREAD

**Issue by jasonkarns** [optimizely/ruby-sdk#247]
While attempting to spike out an implementation for #246 I routinely encountered datafile schema validation errors. However, the validation errors did not provide any insight into the schema violation.

The only output provided was: `E, [2020-04-30T14:16:25.777688 #23143] ERROR -- : Provided datafile is in an invalid format.`

It would be helpful if the validator provided more specific error details beyond "valid / not valid".

The json-schema gem already provides this capability via the `fully_validate` method.

**Comment by Tamara-Barum** [comment]
My apologies for the delay in response to this issue. The team is updating our processes and reviewing all open issues and PR's. If this Feature Request is still relevant, please add your suggestion to our idea portal here https://feedback.optimizely.com/ where it can be evaluated with the other ideas for the product.  From here it will be appropriately prioritized and brought to the engineering team.
