### ISSUE TITLE
[ENHANCEMENT] Add missing information to gemspec for Dependabot to pull it in

### ISSUE THREAD

**Issue by zachfeldman** [optimizely/ruby-sdk#347]
### Description

We recently got a [Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates) pull request filed to update to the 5.0 version of this SDK. The pull request had a few issues:

![image](https://github.com/optimizely/ruby-sdk/assets/1437644/02e44fba-0739-4732-8f00-c162b343ba53)

A) There was no release notes or changelog in the pull request
B) The link back to the library just goes to https://www.optimizely.com/, making it hard to find the codebase and the above information

I think this Gem is missing some fields that would enable Dependabot to pull in this information automatically in its .gemspec file:

```
homepage: The URL of your GitHub repository (e.g., https://github.com/your-username/your-library).
source_code_uri: The URL of your repository's code (usually the same as homepage).
changelog_uri: The URL of your release notes (e.g., https://github.com/your-username/your-library/blob/master/CHANGELOG.md).
```

can the maintainers add these so Dependabot can automatically pull in this information please? 

This and us not looking closer for the notes caused us to miss the change "BatchEventProcessor is now the default EventProcessor when Optimizely::Project is instantiated (#325)." which caused a memory leak in our job processing queue and took it down for a few hours. Our fault for not reading the Changelog ourselves, but it would be so much more convenient if it was included automatically by Dependabot in future updates.

Thanks for your consideration!

### Benefits

We wouldn't miss key updates to the gem in Dependabot pull requests.

**Comment by andrewleap-optimizely** [comment]
@zachfeldman Thanks for bringing this to our attention! We have added the suggested info to the gemspec and cut a release.
